{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel-cortex.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
{{- end }}
